on: [push]

env:
  APP_NAME: myapp
  TEST_TAG: myapp:test

jobs:
  build_container:
    # TODO what host are available? How to test on multiple platforms?
    # strategy:
    #   matrix:
    #     os: [ubuntu-18.04, ubuntu-20.04]
    #     version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build and export to Docker
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .devcontainer/Dockerfile
          load: true
          build-args: |
            LUA_INSTALL_VERSION=5.3.6
            LUAROCKS_INSTALL_VERSION=3.8.0
          # push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          tags: ${{ env.TEST_TAG }}
          outputs: type=docker,dest=/tmp/${{ env.APP_NAME }}.tar


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: /tmp/${{ env.APP_NAME }}.tar

      - name: Test
        run: |
          docker load --input /tmp/${{ env.APP_NAME }}.tar
          docker run --name mycontainer --rm -t ${{ env.TEST_TAG }}

# TODO: Check if there is an easier way!
  # test_docker_image:
  #   runs-on: ubuntu-latest
  #   needs: build_container
  #   steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ env.APP_NAME }}
  #         path: /tmp
  #     - name: Load Docker image
  #       run: |
  #         docker load --input /tmp/${{ env.APP_NAME }}.tar
  #         docker run --name mycontainer --rm -i -t ${{ env.TEST_TAG }}
  #         docker exec -ti mycontainer sh -c "echo Version: \n $(lua -v) && echo $(luarocks --version)"

        